# Placeholder: this plugin currently ships no parser.
#
# Person entries are not generated by a NOMAD parser anymore.  Instead, a
# standalone script reads the members spreadsheet and produces
# `*.archive.json` files that are uploaded directly, where NOMAD's built-in
# archive parser turns them into individual Person entries.
#
# If a parser is reintroduced, define a ParserEntryPoint here and register it
# in pyproject.toml under [project.entry-points.'nomad.plugin'].
